[package]
name = "demoa"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.1"
num-traits = "0.2"
borsh = "0.10"
num-derive = "0.3.3"
thiserror = "1.0.40"

[features]
no-entrypoint = []

[lib]
crate-type = ["cdylib", "lib"]
